### ISSUE TITLE
Please upstream this to meta-fsl-arm-extra

### ISSUE THREAD

**Issue by otavio** [schnitzeltony/meta-variscite-community#1]
Hello Andreas,

It seems you've been doing a great job maintaining the recipes up to date, so it would be great if you could prepare patches to include the machines into meta-fsl-arm-extra :-)

**Comment by schnitzeltony** [comment]
On Thu, Oct 8, 2015 at 8:10 PM, Otavio Salvador <notifications@github.com>
wrote:

> Hello Andreas,
>
> It seems you've been doing a great job maintaining the recipes up to date,
> so it would be great if you could prepare patches to include the machines
> into meta-fsl-arm-extra :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schnitzeltony/meta-variscite-community/issues/1>.
>
Hi Otavio,

yes the final target is meta-fsl-arm-extra but I am currently not yet
satisfied with the quality here - e.g. u-boot dinosaur / many dt-settings
are more ore less guesswork. It would really help if variscite would learn
how to use git for proper rebasing...

Andreas

**Comment by otavio** [comment]
Agreed; they are bad in this regard but if you could start small I could use this to push them as well.

**Comment by otavio** [comment]
As this had not moved forward, I am closing this issue.
